//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACMicropresicion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int IdBitacora { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Accion { get; set; }
        public string TablaAfectada { get; set; }
        public string ContenidoViejo { get; set; }
        public string ContenidoNuevo { get; set; }
        public string UsuarioAgrega { get; set; }
    }
}
