//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACMicropresicion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int IdDetalleCompra { get; set; }
        public short Renglon { get; set; }
        public decimal PrecioTotal { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public int IdCompra { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Material Material { get; set; }
    }
}
