//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACMicropresicion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Compra = new HashSet<Compra>();
            this.DireccionProveedor = new HashSet<DireccionProveedor>();
            this.DireccionUsuario = new HashSet<DireccionUsuario>();
            this.Material = new HashSet<Material>();
            this.TipoMaterial = new HashSet<TipoMaterial>();
            this.Proveedor = new HashSet<Proveedor>();
            this.InfoProveedor = new HashSet<InfoProveedor>();
            this.Producto = new HashSet<Producto>();
            this.TipoProducto = new HashSet<TipoProducto>();
            this.Venta = new HashSet<Venta>();
            this.TipoPago = new HashSet<TipoPago>();
            this.Factura = new HashSet<Factura>();
            this.Usuario = new HashSet<Usuario>();
            this.InfoUsuario = new HashSet<InfoUsuario>();
        }
    
        public int IdEstado { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaAgrega { get; set; }
        public Nullable<System.DateTime> FechaElimina { get; set; }
        public string UsuarioAgrega { get; set; }
        public byte Eliminado { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<DireccionProveedor> DireccionProveedor { get; set; }
        public virtual ICollection<DireccionUsuario> DireccionUsuario { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<TipoMaterial> TipoMaterial { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<InfoProveedor> InfoProveedor { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<TipoProducto> TipoProducto { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual ICollection<TipoPago> TipoPago { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<InfoUsuario> InfoUsuario { get; set; }
    }
}
