//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACMicropresicion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoProveedor
    {

        public InfoProveedor()
        {

        }


        public InfoProveedor(byte tipo, string valor, System.DateTime fechaAgrega, System.DateTime fechaElimina, 
            string UsuarioAgrega, byte eliminado, int IdProveedor, int IdEstado)
        {
            this.Tipo = tipo;
            this.Valor = valor;
            this.FechaAgrega = fechaAgrega;
            this.FechaElimina = fechaElimina;
            this.UsuarioAgrega = UsuarioAgrega;
            this.Eliminado = eliminado;
            this.IdProveedor = IdProveedor;
            this.IdEstado = IdEstado;
        }

        public string toString()
        {
            return "Tipo: " + Tipo + ", Valor: " + Valor + ", Fecha agregado: " + FechaAgrega + ", Fecha Eliminado: " + FechaElimina +
                ", Agregador por: " + UsuarioAgrega + ", Eliminado: " + Eliminado + ", Estado:" + IdEstado;
        }


        public int IdInfoProveedor { get; set; }
        public byte Tipo { get; set; }
        public string Valor { get; set; }
        public System.DateTime FechaAgrega { get; set; }
        public Nullable<System.DateTime> FechaElimina { get; set; }
        public string UsuarioAgrega { get; set; }
        public byte Eliminado { get; set; }
        public int IdProveedor { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
