//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACMicropresicion.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAC_MICROPRECISION_SAEntities : DbContext
    {
        public CAC_MICROPRECISION_SAEntities()
            : base("name=CAC_MICROPRECISION_SAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bitacora> Bitacora { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Compra> Compra { get; set; }
        public DbSet<DetalleCompra> DetalleCompra { get; set; }
        public DbSet<DetalleVenta> DetalleVenta { get; set; }
        public DbSet<DireccionProveedor> DireccionProveedor { get; set; }
        public DbSet<DireccionUsuario> DireccionUsuario { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<InfoProveedor> InfoProveedor { get; set; }
        public DbSet<InfoUsuario> InfoUsuario { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<TipoMaterial> TipoMaterial { get; set; }
        public DbSet<TipoPago> TipoPago { get; set; }
        public DbSet<TipoProducto> TipoProducto { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Venta> Venta { get; set; }
    }
}
