//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACMicropresicion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Compra = new HashSet<Compra>();
            this.DireccionUsuario = new HashSet<DireccionUsuario>();
            this.InfoUsuario = new HashSet<InfoUsuario>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int IdUsuario { get; set; }
        public string Cedula { get; set; }
        public byte Tipo { get; set; }
        public string NombreCompleto { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime FechaAgrega { get; set; }
        public Nullable<System.DateTime> FechaElimina { get; set; }
        public string UsuarioAgrega { get; set; }
        public byte Eliminado { get; set; }
        public int IdEstado { get; set; }
    
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<DireccionUsuario> DireccionUsuario { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<InfoUsuario> InfoUsuario { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }

        public string toString()
        {
            return "Cédula: " + Cedula + ", Tipo: " + Tipo + ", Nombre Completo: " + NombreCompleto +
                ", Primer Apellido: " + PrimerApellido + ", Segundo Apellido: " + SegundoApellido +
                ", Nombre de Usuario: " + NombreUsuario + ", Contraseña: " + Contrasena +
                ", Fecha agregado: " + FechaAgrega + ", Fecha Eliminado: " + FechaElimina +
                ", Agregador por: " + UsuarioAgrega + ", Eliminado: " + Eliminado + ", Estado:" + IdEstado;
        }

    }
}
